### ISSUE TITLE
The item in the java-menu can be multiple add

### ISSUE THREAD

**Issue by moonEEVEEXwX** [kejonaMC/CrossplatForms#119]
### What feature do you want to see added?

Like we write the glass pane,we write it form this:
2:
        display-name: " "
        material: GLASS_PANE
4:
        display-name: " "
        material: GLASS_PANE
5:
        display-name: " "
        material: GLASS_PANE

Into this:
[2,4,5]:
        display-name: " "
        material: GLASS_PANE

### Are there any alternatives?

The Form can be changed like this too
item_name:
        display-name: " "
        spot:[2,4,5]
        materialGLASS_PANE

**Comment by Funasitien** [comment]
Would be very usefull and can reduce the size up to 10 for people which use resource pack menu. A solution could be:
 - check if the name of the object is a number
 - If yes, set slot to [ObjectName]
 - If not, use slot variable in the object

**Comment by Funasitien** [comment]
Little example  :
Case 1:
```yaml
1:
  name: ""
  description: ""
```

Case 2:
```yaml
play_button:
  slot: [1;9], [12;15]
  name: ""
  description: ""
```
