### ISSUE TITLE
Add the possibility to use "should-show" for dropbox options.

### ISSUE THREAD

**Issue by spikehidden** [kejonaMC/CrossplatForms#132]
### What feature do you want to see added?

Add the possibility to use `should-show` for `dropbox` components in custom forms.

#### Ex.:
```yml
form:
  type: custom_form
  title: "title"
  components:
    - type: dropdown
      text: "label"
      default: 0
      options:
      - "option 0"
        should-show:
        - "%placeholder_0%"
      - "option 1"
        should-show:
        - "%placeholder_1%"
      - "option 2"
        should-show:
        - "%placeholder_2%"
```

### Are there any alternatives?

Besides creating an extra form for each option or adding a notice as a lable of what options a user can use? - None.

*And those alternatives are also not really good solutions.*
