### ISSUE TITLE
Parsers doesn't work

### ISSUE THREAD

**Issue by StKillReal** [kejonaMC/CrossplatForms#193]
### Describe the bug

I was looking for a solution in Discord, but have found nothing. It should work, but it doesn't.

```
  menus:
    type: custom_form
    title: "§lБоковые меню"
    components:
      - type: dropdown
        text: "Выбери меню"
        default-option: 0
        options:
          - "Стандартное"
          - "Городское"
          - "Приваты"
          - "Рыночное"
          - "Шахтерское"
          - "Судный день"
        parsers:
          - type: replacements
            replacements:            
              - Стандартное: scoreboard1
              - Городское: town
              - Приваты: wg
              - Рыночное: ah
              - Шахтерское: miner
              - Судный день: wed          
    actions:
      - commands:
          - "player; tab scoreboard show %result_0%" 
```

### To Reproduce

1. Create a pareser for a line
2. It should be enough

### Expected behaviour

%result_0% should be changed on parser

### Screenshots / Videos

![image](https://github.com/kejonaMC/CrossplatForms/assets/60330193/5da8eafb-e934-4a24-98c0-cc7f64f9f2b4)
![image](https://github.com/kejonaMC/CrossplatForms/assets/60330193/6416c562-5afe-4d1a-b15b-2d0a3d59e964)
![image](https://github.com/kejonaMC/CrossplatForms/assets/60330193/bcc3c908-88db-4478-a1e3-5cdc88f4543e)

### CrossplatForms Version

latest build
